version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  node_modules: {}
  python_site_packages: {}
  frontend_dist_files: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  vue:
    build:
      context: .
      dockerfile: ./compose/vue/Dockerfile
    volumes:
      - frontend_dist_files:/app/dist_shared
      - node_modules:/app/node_modules


  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    depends_on:
      - postgres
      - redis
      - vue
    command: /gunicorn.sh
    env_file: .env
    volumes:
      - python_site_packages:/usr/local/lib/python3.5/site-packages
      - frontend_dist_files:/app/frontend/dist_shared


  nginx:
    build: ./compose/nginx
    depends_on:
      - django

      - certbot
    environment:
      - MY_DOMAIN_NAME=e1pam.me

    ports:
      - "0.0.0.0:80:80"

      - "0.0.0.0:443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt

  certbot:
    image: quay.io/letsencrypt/letsencrypt
    command: bash -c "sleep 6 && certbot certonly -n --standalone -d e1pam.me --agree-tos --email nw4869@gmail.com --server https://acme-v01.api.letsencrypt.org/directory --rsa-key-size 4096 --verbose --keep-until-expiring --preferred-challenges http-01"
    entrypoint: ""
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - "80"
      - "443"
    environment:
      - TERM=xterm


  redis:
    image: redis:3.0

#  celeryworker:
#    build:
#      context: .
#      dockerfile: ./compose/django/Dockerfile
#    env_file: .env
#    depends_on:
#     - postgres
#     - redis
#    command: celery -A sagittarius.taskapp worker -l INFO
#    volumes:
#      - python_site_packages:/usr/local/lib/python3.5/site-packages
#
#  celerybeat:
#    build:
#      context: .
#      dockerfile: ./compose/django/Dockerfile
#    env_file: .env
#    depends_on:
#      - postgres
#      - redis
#    command: celery -A sagittarius.taskapp beat -l INFO
#    volumes:
#      - python_site_packages:/usr/local/lib/python3.5/site-packages

